project:
  type: book
  output-dir: _book

book:
  title: "NetStream: Programs for watershed analyses"
  author: "Daniel Miller"
  date: today
  
  page-footer:
    right: \
      This book was created with <a href="https://quarto.org/">Quarto</a>.
      
  chapters:
    - index.qmd
    - intro.qmd
    - prerequisites.qmd
    - part: programs.qmd
      chapters:
      - Bldgrds.qmd
    - part: "Data-field options"
      chapters:
      - attributeLists.qmd
    - part: "Tasks"
      chapters:
      - CreateStreamLayer.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

execute:
  freeze: auto

