# Build a stream layer {#sec-buildStreamLayer}

## Tasks

It seems straightforward: define a flow direction for each DEM cell, iteratively trace flow lines downstream summing cell area as we go to create a flow accumulation raster, set a flow threshold, and voila, a stream layer. That’s basically it, but there are complications. The first two items below discuss issues that are hardwired into bldgrds. Everything else has user-defined options, although default values are built in for most. 

1.  Flow direction from a DEM cell is not uniquely defined. Each cell has 8 adjacent cells. Depending on the shape of the ground surface interpolated from the 9 elevation values at the midpoints of the cells, each adjacent cell may contribute all, some portion, or none of its area to the central cell and the central cell may contribute all, some portion, or none of its area (and the accumulated area of the upslope cells that flows into it) to each of the adjacent cells. The simplest strategy is to have all flow from the central cell go to one of the 8 adjacent cells. This is the “D-8” flow-direction algorithm [(Jenson and Domingue, 1988)](https://www.zotero.org/google-docs/?VqinZF). It provides a poor estimate of contributing area to a cell that is biased by the 8 flow-direction options. One must also decide which of the 8 adjacent cells to direct flow to, and there are a variety of strategies for that. When D-8 flow paths are needed, we use the D8-LTD algorithm [(Orlandini et al., 2003)](https://www.zotero.org/google-docs/?fMB1aB), which corrects for the directional bias. A variety of flow-direction algorithms have been developed that accommodate flow in any direction and can direct flow to multiple downslope adjacent cells [(Wilson et al., 2008)](https://www.zotero.org/google-docs/?hUpxCo) and thus allow for flow dispersion. We use the D-infinity algorithm [(Tarboton, 1997)](https://www.zotero.org/google-docs/?aqvkd0), which allows flow into one or two adjacent cells. Flow accumulation is then calculated using the D-infinity flow directions, until the criteria for channel initiation are met. Downslope of that point, we use D-8 to prevent flow dispersion out of the channel.

2.  Closed depressions. These may be actual depressions with no outflow, in which case all inflowing water infiltrates to groundwater, or they be actual depressions with an outflow not visible from the DEM (e.g., road prisms with culverts), or they may be artifacts or errors in the DEM. In general, we want to define a flow path to an outlet from the DEM for every DEM cell. Even for closed depressions with no outlet, water that flows into them exits through some groundwater flow path and eventually flows to a stream somewhere downslope or out of the area represented with the DEM. Two primary approaches are used to deal with closed depressions.

    1.  Filling. This is the simplest. The depression is filled to the elevation of its lowest pour point (where water would spill out if the depression were filled). Flow directions through the closed depression are then directed toward the pour point. This option destroys any information about flow directions within the closed depression, which we would rather avoid.

    2.  Carving. A path is carved from the depression pour point to the lowest point in the depression and from to a location along the flow path from the pour point where the elevation becomes less than or equal to the lowest point in the depression. Flow within the depression is then directed to the lowest point and then out of the depression along the carved path [(Soille et al., 2003)](https://www.zotero.org/google-docs/?OXcgwW). The flow paths from the pour point heading into and away from the depression follow D8-LTD flow directions. This is the preferred option and the one used in bldgrds. 

3.  Channel initiation. We need to specify the conditions where channels initiate. This determines the upslope extent of the channel network and the channel density. We have several strategies:

    1.  Local topographic position. For high-resolution DEMs interpolated from high-density ground returns (e.g., \>1/m2), channels are visible directly in the DEM. Channels can be highlighted using a measure of local topographic position (LTP), which provides an indicator of the elevation of a DEM grid point relative to its neighbors. Absolute LTP measures give the difference in elevation of the grid point compared to the mean or median grid-point elevations within a specified circular neighborhood. Relative measures normalize that elevation difference by some measure of elevation variability in the neighborhood. Deviation from mean elevation (DEV), for example, divides the difference from mean elevation by the standard deviation of DEM grid-point elevations within the neighborhood [(Newman et al., 2018)](https://www.zotero.org/google-docs/?LBmh8g). Thus, a small channel incised 0.25 meters traversing flat, low-relief terrain (with a small standard deviation in elevation values) will have a large DEV value compared to a small channel incised 0.25 meters traversing steep, rough terrain (with a larger standard deviation). For determining upslope channel extent, we can specify an LTP threshold value and exclude channel initiation in areas where the LTP value is greater than that threshold (i.e., channel incision is too small). One must decide on whether to use an absolute or relative measure and on the appropriate length scale for the local neighborhood. I find an absolute measure easier to interpret than a relative measure, because it provides a direct estimate of the depth of channel incision; I can decide that traced channels begin only when a channel is incised to more than 0.2 meters (LTP \< -0.2), for example. The radius to choose for the local neighborhood should be set relative to the resolution of the DEM, the roughness of the terrain (greater roughness requires larger neighborhoods), and the smallest width of channels you want to identify. Typically, at their upslope extent, channels are less than a meter wide, so a radius of five meters or more will suffice for calculating LTP. See slides 1-2 for examples in the Sprague basin. 

    2.  Area-slope threshold. Where the ground-return point density is insufficient to resolve channels at their upslope extent, we need to infer channel-initiation locations. One strategy for this is to estimate where on the landscape there is sufficient flowing water to erode a channel. The contributing (drainage) area to any point on the landscape indicates the upslope area from which overland flow and water infiltrating to shallow subsurface flow through the soil can originate. Hence, differences in contributing area provide indicators of relative differences in overland- and shallow-subsurface discharge; greater contributing area implies greater discharge. This is the idea behind using thresholds in contributing area to estimate upslope channel extent: for a given climate and terrain, some minimum contributing area is required for sufficient discharge to erode a channel. The erosive power of water depends not only on how much water there is, but also on the steepness of the slope it is flowing over or through. Hence, threshold values for functions of contributing area and ground-surface slope may provide better indicators of where channels initiate than contributing area alone. We use the function ASe, where A is contributing area, S is tangent of the ground-surface gradient, and e is a user-specified exponent [(Montgomery and Foufoula-Georgiou, 1993)](https://www.zotero.org/google-docs/?oLMSBx). Contributing area may be specified as specific contributing area, which is the contributing area divided by the length of a contour line crossed by flow exiting the DEM cell [(Gallant and Hutchinson, 2011)](https://www.zotero.org/google-docs/?x6ado8). This accounts for effects of topographic convergence and divergence on the depth of flow and is the default in bldgrds. 

Basin topography is found to exhibit certain scaling relationships between contributing area and gradient that delineate divergent, convergent, and channelized topography [(Ijjasz-Vasquez and Bras, 1995)](https://www.zotero.org/google-docs/?jPSX2w). We capitalize on these to calibrate threshold values for channel initiation. Following Clarke et al. [(2008)](https://www.zotero.org/google-docs/?uZuu38), we plot channel density as a function of the ASe value and look for the inflection in log-log plots that indicate a transition to the channelized regime. See Slide 4. This provides a ball-park estimate of the threshold value appropriate for the terrain as represented with the DEM. Plots are produced separately for steep terrain and low-gradient terrain, under the assumption that channel-forming processes may differ, e.g., landsliding on steep terrain and fluvial erosion on low-gradient terrain. See examples in Slides 4-5. 

3.  Plan curvature. Plan curvature measures the rate of change in elevation measured in a direction tangent to a contour line; it indicates the curvature of the contour. Tangential curvature is similar, but measures the rate of change relative to a plane oriented tangent to the ground surface, whereas plan curvature measures curvature relative to a horizontal plane [(Minár et al., 2020)](https://www.zotero.org/google-docs/?vW7Pg0). Both provide another measure for topographic indication of presence of a channel. Bldgrds has the option to specify thresholds of plan (or tangential) curvature for channel initiation. These thresholds can be determined by building curvature rasters using the makegrids program, classifying by proposed threshold values, and plotting on a shaded relief image to see where a proposed threshold would allow channel initiation. The LTP thresholds described above provide a similar and more easily interpreted method of using topography inferred from the DEM for identifying channels.

4.  Minimum flow length. Bldgrds iteratively traverses every flow path within a DEM in a downslope direction and checks each cell to see if it meets the channel-initiation criteria. As seen in the images of slides 1, 2, and 5, the criteria can be met for some portion of the flow path, but then no longer be met further downslope. Bldgrds requires specification of the minimum length over which the initiation criteria must be met before it will initialize a channel. The appropriate length depends on the resolution of the DEM and on the roughness of the terrain. If topographic channel indicators are indistinct, small zones where initiation thresholds are met can arise from noise in the DEM or small-scale roughness in the terrain. 

<!-- -->

4.  Channel courses. The cell-to-cell D8 flow paths used once channel initiation is met do not always follow the same course that the actual channels do. Sometimes evidence of the channel flow path is not visible in the DEM, sometimes there are multiple options, sometimes noise in the DEM misdirects the flow path. It can help to use information from DEM cells beyond those immediately adjacent and to bring in information from other data sources. Here are options used by bldgrds.

    1.  Flow indicators. Topographic indicators of a channel can also be used to guide channelized flow paths. The flowcat program (for flow categorization) uses one to four such indicators: 1) a threshold in flow accumulation calculated with D-infinity flow directions and no channel initiation, 2) geomorphon valley and pit types [(Stepinski and Jasiewicz. J, 2011; Jasiewicz and Stepinski, 2013)](https://www.zotero.org/google-docs/?jeLPXk), 3) a threshold in plan (or tangential) curvature, and 4) a threshold for deviation from mean elevation (DEV). FlowCat creates a raster with each cell indicating the number of specified flow indicators that are met at each DEM cell. If all four indicators are used, then raster values range from 0 to 4. Bldgrds preferentially directs channels towards raster-cell values greater than zero, or greater than a specified minimum (e.g., if all four indicators are used, a minimum of two indicators must be met). This is done by excavating the corresponding cells in the DEM by a multiple of the flow-indicator raster. 

    2.  Water mask. Infrared laser signals are absorbed by water so there are no signal returns from open water. Lidar DEMs often have areas of water “hydroflattened”, so that the open-water zone has a single uniform elevation or a uniformly downstream decreasing elevation. In other cases, elevations over the open-water zone are interpolated from ground returns on either side, which can generate noisy DEM elevation values through the zone of open water. This can result in zig-zaggy flow paths, which then overestimate channel length and affect values of corresponding derivatives, such channel gradient. We want channel flow paths through zones of open water to be smooth and to track through the center of the open-water zone. To accomplish that, provide bldgrds with a separate raster or polygonal water-mask layer. Bldgrds will direct flow paths through the center of these zones. In some cases, breaklines for hydroflattening are provided with lidar-derived DEMs. In other cases, we can build a water mask using multi-band imagery. Open water appears dark in infra-red bands and can be delineated using image segmentation. Program waterMaskByTopo can generate a water-mask raster using the infrared band from e.g., NAIP. It also uses thresholds in DEV and gradient to distinguish shadows. 

    3.  DEM derivatives. Azimuth, plan curvature, and the direction of steepest descent can also be used with varying degrees of influence to guide channelized flow directions. Azimuth and plan curvature are measured over a specified length scale. By specifying a length greater than the DEM grid-point spacing, azimuth and curvature use information beyond the elevation of adjacent points, which can reduce the influence of noise in the DEM. It can also cause flow paths to deviate from the steepest-descent path to an adjacent cell. One or more of these indicators may be used and, if more than one are specified, different degrees of influence can be specified for each. The choice of indicators, of length scales, and of the degree of influence to specify requires iterative experimentation.

    4.  Flow diversions. High-resolution lidar DEMs resolve road prisms and other potential blockages to channel flow. The carving algorithm used to drain closed depressions will often trace the correct flow path, but not in all cases. If these apparent blockages have drainage structures, such as culverts, not visible in the DEM, these need to be specified from other data sources. Typically, such other data sources are not available, and the likely locations of culverts need to be manually digitized. This task is iterative: building a stream layer, looking for diversions, digitizing a culvert or drainage location, rebuilding the stream layer, and repeating until satisfied with the stream layer. 

With high-resolution DEMs, a default strategy for channel initiation and flow-path routing is:

Channel initiation. 

-   Use thresholds of local relief for low- and high-gradient terrain, along with 

-   area-slope thresholds to limit the extent that channel features resolvable in the DEM are traced upslope. 

Channelized flow routing. 

-   Use elevation derivatives of azimuth and plan curvature, with these values calculated over length scales sufficient to span several DEM cells. 

-   Use a water mask derived using the waterMaskByTopo program with the infrared NAIP band. 

-   Iterative correction of flow diversions.

## Linked node data structure

The channel network traced by bldgrds is represented using a [linked-node data structure](https://en.wikipedia.org/wiki/Linked_data_structure). A channel node is created for each DEM grid point along the channel flow path. Each channel node is connected to one or more upstream nodes and to one downstream node. (The data structure can accommodate multiple downstream nodes, but I haven’t fully implemented that yet. We need it to route through anastomosing channel networks, but I’m still working on efficient and robust ways to trace through networks with multiple loops). Each node has an associated set of attributes. This set may include such attributes as elevation, contributing area, channel geometry, channel gradient, and a variety of others available through instructions specified in the input files to the programs. Each node is associated with a DEM grid point, but node locations may be displaced from the grid point to accommodate smooth flow paths. 

Bldgrds builds a binary data file that stores the channel-node list that specifies the node locations and the node-to-node connections. Any subsequent program that uses the traced channel network reads this file to construct the channel network. The file is named nodeNet_ID.dat, where “ID” is a text string used to identify a dataset. 
